# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 03:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20190807_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='题目答案'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='题目详情'),
        ),
    ]
